name: Github Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install firmware dependencies
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install MD_Parola
      - name: Build firmware
        run: arduino-cli compile -b arduino:avr:uno --build-path ./build ./firmware
      - name: Deploy to Pages
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        id: deploy_to_pages
