name: Github Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build firmware
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"
          sketch-paths: |
            - build
          libraries: |
            - name: MD_Parola
      - name: Deploy to Pages
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        id: deploy_to_pages
